### ISSUE TITLE
1.12 build

### ISSUE THREAD

**Issue by Dominance** [MCUpdater/IGI-Addon-ToughAsNails#1]
Hey man noticed you got the 1.11.2 update out was hoping for a 1.12 one as well 🥇

**Comment by smbarbour** [comment]
Well, since InGame Info XML just updated to 1.12 a few hours ago, it should be possible now.  I'll get to it as soon as I can.

**Comment by Dominance** [comment]
Thanks a bunch!

**Comment by agentwolf88** [comment]
Is the 1.12.2 Version released?

**Comment by smbarbour** [comment]
Doh... I had forgotten about this. I'll see about whipping it up tonight

**Comment by agentwolf88** [comment]
This would be realy nice!

**Comment by agentwolf88** [comment]
Any news?

**Comment by agentwolf88** [comment]
When will release the update? Please do it. :(

**Comment by smbarbour** [comment]
Yesterday.  https://minecraft.curseforge.com/projects/in-game-info-xml-addon-tough-as-nails/files/2517111
